name: Daily Sponsor Update

on:
    schedule:
        # Runs at 8:45 AM, every Saturday
        - cron: "45 8 * * 6"
    workflow_dispatch:
        # Allows manual triggering from the GitHub Actions UI

permissions:
    contents: write

jobs:
    update-data:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Run Update Script
              # Injects the GitHub Variable into the Node.js process
              env:
                  GOV_PAGE_URL: 'https://www.gov.uk/government/publications/register-of-licensed-sponsors-workers'
              run: node update.js

            - name: Commit and Push Changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action Bot"
                  git add data/
                  git commit -m "Automated daily sponsor list split update" || exit 0
                  git push
